name: khazana_fintech_task
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  intl: ^0.19.0
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4
  syncfusion_flutter_charts: ^26.2.10

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
